version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/master/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/worker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
